export type Cocktail = {
  idDrink?: string
  strDrink: string
  strDrinkAlternate?: null
  strTags?: string
  strVideo?: null
  strCategory?: string
  strIBA?: string
  strAlcoholic?: string
  strGlass?: string
  strInstructions?: string
  strInstructionsES?: null
  strInstructionsDE?: string
  strInstructionsFR?: null
  strInstructionsIT?: string
  'strInstructionsZH-HANS'?: null
  'strInstructionsZH-HANT'?: null
  strDrinkThumb: string
  strIngredient1?: string
  strIngredient2?: string
  strIngredient3?: string
  strIngredient4?: string
  strIngredient5?: null
  strIngredient6?: null
  strIngredient7?: null
  strIngredient8?: null
  strIngredient9?: null
  strIngredient10?: null
  strIngredient11?: null
  strIngredient12?: null
  strIngredient13?: null
  strIngredient14?: null
  strIngredient15?: null
  strMeasure1?: string
  strMeasure2?: string
  strMeasure3?: string
  strMeasure4?: null
  strMeasure5?: null
  strMeasure6?: null
  strMeasure7?: null
  strMeasure8?: null
  strMeasure9?: null
  strMeasure10?: null
  strMeasure11?: null
  strMeasure12?: null
  strMeasure13?: null
  strMeasure14?: null
  strMeasure15?: null
  strImageSource?: string
  strImageAttribution?: string
  strCreativeCommonsConfirmed?: string
  dateModified?: Date
}
